//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pousada
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.Financeiro = new HashSet<Financeiro>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public System.DateTime nascimento { get; set; }
        public System.DateTime datainicio { get; set; }
        public string filiacao { get; set; }
        public string endereco { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string email { get; set; }
        public string telefoneresidencial { get; set; }
        public string telefonecelular { get; set; }
        public string telefonecomercial { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> datafim { get; set; }
        public string curso { get; set; }
        public string universidade { get; set; }
        public string observacoes { get; set; }
    
        public virtual ICollection<Financeiro> Financeiro { get; set; }
    }
}
