//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pousada
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financeiro
    {
        public int id { get; set; }
        public bool entrada { get; set; }
        public int alunoid { get; set; }
        public string valor { get; set; }
        public Nullable<System.DateTime> vencimento { get; set; }
    
        public virtual Aluno Aluno { get; set; }
    }
}
